title: Abdullah Canbolat
logo: "/images/portrait.JPG?raw=true"
description: >
  Experienced Full Stack Web Developer with expertise in front-end and back-end development.
  Committed to delivering high-quality, scalable web applications, continuous learning and professional development.
  <br><br>
  Skills
  Front End: React.js, Vue.js, JQuery, CSS, HTML, Bootstrap, React Native
  Back End: Node.js, Python, Django, Docker, Kubernetes, Nginx
  Databases: MongoDB, MySQL, PostgreSQL, Firebase
  <br><br>
  <a href="https://www.linkedin.com/in/abdullah-talha-canbolat-6ab794109/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
